// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForCreateCodes implements pgx.CopyFromSource.
type iteratorForCreateCodes struct {
	rows                 []CreateCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BatchID,
		r.rows[0].Code,
	}, nil
}

func (r iteratorForCreateCodes) Err() error {
	return nil
}

func (q *Queries) CreateCodes(ctx context.Context, arg []CreateCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"codes"}, []string{"batch_id", "code"}, &iteratorForCreateCodes{rows: arg})
}
