// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchStatus string

const (
	BatchStatusActive   BatchStatus = "active"
	BatchStatusDisabled BatchStatus = "disabled"
)

func (e *BatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatchStatus(s)
	case string:
		*e = BatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatchStatus: %T", src)
	}
	return nil
}

type NullBatchStatus struct {
	BatchStatus BatchStatus `json:"batch_status"`
	Valid       bool        `json:"valid"` // Valid is true if BatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatchStatus), nil
}

type CodeStatus string

const (
	CodeStatusUnused   CodeStatus = "unused"
	CodeStatusDisabled CodeStatus = "disabled"
)

func (e *CodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CodeStatus(s)
	case string:
		*e = CodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CodeStatus: %T", src)
	}
	return nil
}

type NullCodeStatus struct {
	CodeStatus CodeStatus `json:"code_status"`
	Valid      bool       `json:"valid"` // Valid is true if CodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CodeStatus), nil
}

type RedemptionResult string

const (
	RedemptionResultSuccess               RedemptionResult = "success"
	RedemptionResultInvalidInput          RedemptionResult = "invalid_input"
	RedemptionResultInvalidCode           RedemptionResult = "invalid_code"
	RedemptionResultCodeDisabled          RedemptionResult = "code_disabled"
	RedemptionResultBatchDisabled         RedemptionResult = "batch_disabled"
	RedemptionResultExpired               RedemptionResult = "expired"
	RedemptionResultCodeUsedUp            RedemptionResult = "code_used_up"
	RedemptionResultUserLimit             RedemptionResult = "user_limit"
	RedemptionResultRateLimited           RedemptionResult = "rate_limited"
	RedemptionResultCredentialUnavailable RedemptionResult = "credential_unavailable"
)

func (e *RedemptionResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RedemptionResult(s)
	case string:
		*e = RedemptionResult(s)
	default:
		return fmt.Errorf("unsupported scan type for RedemptionResult: %T", src)
	}
	return nil
}

type NullRedemptionResult struct {
	RedemptionResult RedemptionResult `json:"redemption_result"`
	Valid            bool             `json:"valid"` // Valid is true if RedemptionResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRedemptionResult) Scan(value interface{}) error {
	if value == nil {
		ns.RedemptionResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RedemptionResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRedemptionResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RedemptionResult), nil
}

type WebhookStatus string

const (
	WebhookStatusNone       WebhookStatus = "none"
	WebhookStatusPending    WebhookStatus = "pending"
	WebhookStatusSuccess    WebhookStatus = "success"
	WebhookStatusFailed     WebhookStatus = "failed"
	WebhookStatusDeadLetter WebhookStatus = "dead_letter"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhook_status"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type Admin struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	PasswordHash   string    `json:"password_hash"`
	SessionVersion int64     `json:"session_version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Batch struct {
	ID                 int64              `json:"id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	PayloadJson        json.RawMessage    `json:"payload_json"`
	Prefix             string             `json:"prefix"`
	CodeLength         int32              `json:"code_length"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	MaxUsesPerCode     int32              `json:"max_uses_per_code"`
	MaxRedeemsPerUser  int32              `json:"max_redeems_per_user"`
	WebhookUrl         string             `json:"webhook_url"`
	WebhookSecret      string             `json:"webhook_secret"`
	Status             BatchStatus        `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	AssignCredential   bool               `json:"assign_credential"`
	CredentialPlanType string             `json:"credential_plan_type"`
}

type Code struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Code      string     `json:"code"`
	Status    CodeStatus `json:"status"`
	UseCount  int32      `json:"use_count"`
	CreatedAt time.Time  `json:"created_at"`
}

type Credential struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PlanType     string             `json:"plan_type"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Data         json.RawMessage    `json:"data"`
	Used         bool               `json:"used"`
	RedemptionID *int64             `json:"redemption_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type FaqItem struct {
	ID        int64     `json:"id"`
	SortOrder int32     `json:"sort_order"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type IdempotencyKey struct {
	ID           int64     `json:"id"`
	Key          string    `json:"key"`
	RequestHash  []byte    `json:"request_hash"`
	ResponseBody []byte    `json:"response_body"`
	CreatedAt    time.Time `json:"created_at"`
}

type Redemption struct {
	ID              int64            `json:"id"`
	CodeID          *int64           `json:"code_id"`
	BatchID         *int64           `json:"batch_id"`
	CodeText        string           `json:"code_text"`
	UserID          string           `json:"user_id"`
	UserKey         string           `json:"user_key"`
	PayloadSnapshot json.RawMessage  `json:"payload_snapshot"`
	Result          RedemptionResult `json:"result"`
	Message         string           `json:"message"`
	WebhookStatus   WebhookStatus    `json:"webhook_status"`
	WebhookResponse string           `json:"webhook_response"`
	WebhookAttempt  int32            `json:"webhook_attempt"`
	Ip              netip.Addr       `json:"ip"`
	IdempotencyKey  *string          `json:"idempotency_key"`
	EventID         *string          `json:"event_id"`
	CreatedAt       time.Time        `json:"created_at"`
}

type SiteSetting struct {
	Singleton       bool      `json:"singleton"`
	SiteTitle       string    `json:"site_title"`
	LogoData        []byte    `json:"logo_data"`
	LogoContentType *string   `json:"logo_content_type"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type WebhookOutbox struct {
	ID             int64              `json:"id"`
	EventID        string             `json:"event_id"`
	RedemptionID   int64              `json:"redemption_id"`
	Status         WebhookStatus      `json:"status"`
	ScheduledAt    time.Time          `json:"scheduled_at"`
	LeaseToken     *string            `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Attempts       int32              `json:"attempts"`
	LastResponse   string             `json:"last_response"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}
