// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableCredentialsByPlan = `-- name: CountAvailableCredentialsByPlan :one
SELECT COUNT(*)
FROM credentials
WHERE plan_type = $1
  AND used = false
  AND (expired IS NULL OR expired > NOW())
`

func (q *Queries) CountAvailableCredentialsByPlan(ctx context.Context, planType string) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableCredentialsByPlan, planType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodesByBatch = `-- name: CountCodesByBatch :one
SELECT COUNT(*) FROM codes WHERE batch_id = $1
`

func (q *Queries) CountCodesByBatch(ctx context.Context, batchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesByBatch, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodesByBatchAndState = `-- name: CountCodesByBatchAndState :one
SELECT COUNT(*) FROM codes c
JOIN batches b ON b.id = c.batch_id
WHERE c.batch_id = $1
  AND (
      CASE
          WHEN c.status = 'disabled' THEN 'disabled'
          WHEN c.use_count >= b.max_uses_per_code THEN 'used'
          WHEN c.use_count > 0 THEN 'partused'
          ELSE 'active'
      END
  ) = $2::text
`

type CountCodesByBatchAndStateParams struct {
	BatchID int64  `json:"batch_id"`
	State   string `json:"state"`
}

func (q *Queries) CountCodesByBatchAndState(ctx context.Context, arg CountCodesByBatchAndStateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesByBatchAndState, arg.BatchID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCredentials = `-- name: CountCredentials :one
SELECT COUNT(*) FROM credentials
WHERE (
    $1::text = 'all'
    OR ($1::text = 'used' AND used = true)
    OR ($1::text = 'unused' AND used = false)
)
`

func (q *Queries) CountCredentials(ctx context.Context, stateFilter string) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentials, stateFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCredentialsByStatus = `-- name: CountCredentialsByStatus :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE used = true) AS used,
    COUNT(*) FILTER (WHERE used = false) AS unused
FROM credentials
`

type CountCredentialsByStatusRow struct {
	Total  int64 `json:"total"`
	Used   int64 `json:"used"`
	Unused int64 `json:"unused"`
}

func (q *Queries) CountCredentialsByStatus(ctx context.Context) (CountCredentialsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countCredentialsByStatus)
	var i CountCredentialsByStatusRow
	err := row.Scan(&i.Total, &i.Used, &i.Unused)
	return i, err
}

const countRedemptions = `-- name: CountRedemptions :one
SELECT COUNT(*) FROM redemptions
WHERE ($1::bigint = 0 OR batch_id = $1::bigint)
  AND ($2::text = '' OR result::text = $2::text)
  AND ($3::text = '' OR webhook_status::text = $3::text)
  AND ($4::text = '' OR user_key ILIKE '%' || $4::text || '%')
`

type CountRedemptionsParams struct {
	BatchID       int64  `json:"batch_id"`
	ResultFilter  string `json:"result_filter"`
	WebhookFilter string `json:"webhook_filter"`
	UserFilter    string `json:"user_filter"`
}

func (q *Queries) CountRedemptions(ctx context.Context, arg CountRedemptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRedemptions,
		arg.BatchID,
		arg.ResultFilter,
		arg.WebhookFilter,
		arg.UserFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash, session_version, created_at, updated_at
`

type CreateAdminParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Username, arg.PasswordHash)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.SessionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (
    name, description, payload_json, prefix, code_length,
    expires_at, max_uses_per_code, max_redeems_per_user,
    webhook_url, webhook_secret, assign_credential, credential_plan_type, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, name, description, payload_json, prefix, code_length, expires_at, max_uses_per_code, max_redeems_per_user, webhook_url, webhook_secret, status, created_at, updated_at, assign_credential, credential_plan_type
`

type CreateBatchParams struct {
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	PayloadJson        json.RawMessage    `json:"payload_json"`
	Prefix             string             `json:"prefix"`
	CodeLength         int32              `json:"code_length"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	MaxUsesPerCode     int32              `json:"max_uses_per_code"`
	MaxRedeemsPerUser  int32              `json:"max_redeems_per_user"`
	WebhookUrl         string             `json:"webhook_url"`
	WebhookSecret      string             `json:"webhook_secret"`
	AssignCredential   bool               `json:"assign_credential"`
	CredentialPlanType string             `json:"credential_plan_type"`
	Status             BatchStatus        `json:"status"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRow(ctx, createBatch,
		arg.Name,
		arg.Description,
		arg.PayloadJson,
		arg.Prefix,
		arg.CodeLength,
		arg.ExpiresAt,
		arg.MaxUsesPerCode,
		arg.MaxRedeemsPerUser,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.AssignCredential,
		arg.CredentialPlanType,
		arg.Status,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PayloadJson,
		&i.Prefix,
		&i.CodeLength,
		&i.ExpiresAt,
		&i.MaxUsesPerCode,
		&i.MaxRedeemsPerUser,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignCredential,
		&i.CredentialPlanType,
	)
	return i, err
}

const createCode = `-- name: CreateCode :exec
INSERT INTO codes (batch_id, code)
VALUES ($1, $2)
`

type CreateCodeParams struct {
	BatchID int64  `json:"batch_id"`
	Code    string `json:"code"`
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) error {
	_, err := q.db.Exec(ctx, createCode, arg.BatchID, arg.Code)
	return err
}

type CreateCodesParams struct {
	BatchID int64  `json:"batch_id"`
	Code    string `json:"code"`
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (email, plan_type, expired, data)
VALUES ($1, $2, $3, $4)
RETURNING id, email, plan_type, expired, data, used, redemption_id, created_at, updated_at
`

type CreateCredentialParams struct {
	Email    string             `json:"email"`
	PlanType string             `json:"plan_type"`
	Expired  pgtype.Timestamptz `json:"expired"`
	Data     json.RawMessage    `json:"data"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.Email,
		arg.PlanType,
		arg.Expired,
		arg.Data,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PlanType,
		&i.Expired,
		&i.Data,
		&i.Used,
		&i.RedemptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFAQ = `-- name: CreateFAQ :one
INSERT INTO faq_items (sort_order, title, content)
VALUES (
    COALESCE((SELECT MAX(sort_order) FROM faq_items), 0) + 1,
    $1, $2
)
RETURNING id, sort_order, title, content, created_at, updated_at
`

type CreateFAQParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateFAQ(ctx context.Context, arg CreateFAQParams) (FaqItem, error) {
	row := q.db.QueryRow(ctx, createFAQ, arg.Title, arg.Content)
	var i FaqItem
	err := row.Scan(
		&i.ID,
		&i.SortOrder,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_hash)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
RETURNING id, key, request_hash, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	Key         string `json:"key"`
	RequestHash []byte `json:"request_hash"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.Key, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO redemptions (
    code_id, batch_id, code_text, user_id, user_key,
    payload_snapshot, result, message, webhook_status,
    webhook_attempt, ip, idempotency_key, event_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
RETURNING id, code_id, batch_id, code_text, user_id, user_key, payload_snapshot, result, message, webhook_status, webhook_response, webhook_attempt, ip, idempotency_key, event_id, created_at
`

type CreateRedemptionParams struct {
	CodeID          *int64           `json:"code_id"`
	BatchID         *int64           `json:"batch_id"`
	CodeText        string           `json:"code_text"`
	UserID          string           `json:"user_id"`
	UserKey         string           `json:"user_key"`
	PayloadSnapshot json.RawMessage  `json:"payload_snapshot"`
	Result          RedemptionResult `json:"result"`
	Message         string           `json:"message"`
	WebhookStatus   WebhookStatus    `json:"webhook_status"`
	WebhookAttempt  int32            `json:"webhook_attempt"`
	Ip              netip.Addr       `json:"ip"`
	IdempotencyKey  *string          `json:"idempotency_key"`
	EventID         *string          `json:"event_id"`
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, createRedemption,
		arg.CodeID,
		arg.BatchID,
		arg.CodeText,
		arg.UserID,
		arg.UserKey,
		arg.PayloadSnapshot,
		arg.Result,
		arg.Message,
		arg.WebhookStatus,
		arg.WebhookAttempt,
		arg.Ip,
		arg.IdempotencyKey,
		arg.EventID,
	)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.BatchID,
		&i.CodeText,
		&i.UserID,
		&i.UserKey,
		&i.PayloadSnapshot,
		&i.Result,
		&i.Message,
		&i.WebhookStatus,
		&i.WebhookResponse,
		&i.WebhookAttempt,
		&i.Ip,
		&i.IdempotencyKey,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookOutboxEvent = `-- name: CreateWebhookOutboxEvent :one
INSERT INTO webhook_outbox (event_id, redemption_id, status, scheduled_at)
VALUES ($1, $2, 'pending', NOW())
RETURNING id, event_id, redemption_id, status, scheduled_at, lease_token, lease_expires_at, attempts, last_response, created_at, updated_at
`

type CreateWebhookOutboxEventParams struct {
	EventID      string `json:"event_id"`
	RedemptionID int64  `json:"redemption_id"`
}

func (q *Queries) CreateWebhookOutboxEvent(ctx context.Context, arg CreateWebhookOutboxEventParams) (WebhookOutbox, error) {
	row := q.db.QueryRow(ctx, createWebhookOutboxEvent, arg.EventID, arg.RedemptionID)
	var i WebhookOutbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.RedemptionID,
		&i.Status,
		&i.ScheduledAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const deleteCredentialsByIDs = `-- name: DeleteCredentialsByIDs :execrows
DELETE FROM credentials WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteCredentialsByIDs(ctx context.Context, dollar_1 []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredentialsByIDs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFAQ = `-- name: DeleteFAQ :exec
DELETE FROM faq_items WHERE id = $1
`

func (q *Queries) DeleteFAQ(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFAQ, id)
	return err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, session_version, created_at, updated_at
FROM admins
WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.SessionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, name, description, payload_json, prefix, code_length, expires_at, max_uses_per_code, max_redeems_per_user, webhook_url, webhook_secret, status, created_at, updated_at, assign_credential, credential_plan_type FROM batches WHERE id = $1
`

func (q *Queries) GetBatchByID(ctx context.Context, id int64) (Batch, error) {
	row := q.db.QueryRow(ctx, getBatchByID, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PayloadJson,
		&i.Prefix,
		&i.CodeLength,
		&i.ExpiresAt,
		&i.MaxUsesPerCode,
		&i.MaxRedeemsPerUser,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignCredential,
		&i.CredentialPlanType,
	)
	return i, err
}

const getBatchCounts = `-- name: GetBatchCounts :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE c.status = 'disabled') AS disabled,
    COUNT(*) FILTER (WHERE c.use_count >= b.max_uses_per_code AND c.status != 'disabled') AS usedup,
    COALESCE(SUM(c.use_count), 0)::bigint AS total_uses
FROM codes c
JOIN batches b ON b.id = c.batch_id
WHERE c.batch_id = $1
`

type GetBatchCountsRow struct {
	Total     int64 `json:"total"`
	Disabled  int64 `json:"disabled"`
	Usedup    int64 `json:"usedup"`
	TotalUses int64 `json:"total_uses"`
}

func (q *Queries) GetBatchCounts(ctx context.Context, batchID int64) (GetBatchCountsRow, error) {
	row := q.db.QueryRow(ctx, getBatchCounts, batchID)
	var i GetBatchCountsRow
	err := row.Scan(
		&i.Total,
		&i.Disabled,
		&i.Usedup,
		&i.TotalUses,
	)
	return i, err
}

const getCodeByCode = `-- name: GetCodeByCode :one
SELECT c.id, c.batch_id, c.code, c.status, c.use_count, c.created_at, b.name AS batch_name, b.status AS batch_status, b.prefix,
       b.payload_json, b.expires_at, b.max_uses_per_code, b.max_redeems_per_user,
       b.webhook_url, b.assign_credential, b.credential_plan_type
FROM codes c
JOIN batches b ON b.id = c.batch_id
WHERE c.code = $1
FOR UPDATE OF c
`

type GetCodeByCodeRow struct {
	ID                 int64              `json:"id"`
	BatchID            int64              `json:"batch_id"`
	Code               string             `json:"code"`
	Status             CodeStatus         `json:"status"`
	UseCount           int32              `json:"use_count"`
	CreatedAt          time.Time          `json:"created_at"`
	BatchName          string             `json:"batch_name"`
	BatchStatus        BatchStatus        `json:"batch_status"`
	Prefix             string             `json:"prefix"`
	PayloadJson        json.RawMessage    `json:"payload_json"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	MaxUsesPerCode     int32              `json:"max_uses_per_code"`
	MaxRedeemsPerUser  int32              `json:"max_redeems_per_user"`
	WebhookUrl         string             `json:"webhook_url"`
	AssignCredential   bool               `json:"assign_credential"`
	CredentialPlanType string             `json:"credential_plan_type"`
}

func (q *Queries) GetCodeByCode(ctx context.Context, code string) (GetCodeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCodeByCode, code)
	var i GetCodeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Code,
		&i.Status,
		&i.UseCount,
		&i.CreatedAt,
		&i.BatchName,
		&i.BatchStatus,
		&i.Prefix,
		&i.PayloadJson,
		&i.ExpiresAt,
		&i.MaxUsesPerCode,
		&i.MaxRedeemsPerUser,
		&i.WebhookUrl,
		&i.AssignCredential,
		&i.CredentialPlanType,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, email, plan_type, expired, data, used, redemption_id, created_at, updated_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id int64) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PlanType,
		&i.Expired,
		&i.Data,
		&i.Used,
		&i.RedemptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyRedemptions = `-- name: GetDailyRedemptions :many
WITH days AS (
    SELECT generate_series(
        DATE_TRUNC('day', NOW()) - INTERVAL '13 days',
        DATE_TRUNC('day', NOW()),
        INTERVAL '1 day'
    )::date AS date
)
SELECT
    d.date,
    COUNT(r.id) FILTER (WHERE r.result = 'success') AS count
FROM days d
LEFT JOIN redemptions r
  ON r.created_at >= d.date::timestamptz
 AND r.created_at < d.date::timestamptz + INTERVAL '1 day'
 AND r.created_at >= DATE_TRUNC('day', NOW()) - INTERVAL '13 days'
GROUP BY d.date
ORDER BY d.date ASC
`

type GetDailyRedemptionsRow struct {
	Date  pgtype.Date `json:"date"`
	Count int64       `json:"count"`
}

func (q *Queries) GetDailyRedemptions(ctx context.Context) ([]GetDailyRedemptionsRow, error) {
	rows, err := q.db.Query(ctx, getDailyRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyRedemptionsRow
	for rows.Next() {
		var i GetDailyRedemptionsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFAQByID = `-- name: GetFAQByID :one
SELECT id, sort_order, title, content, created_at, updated_at FROM faq_items WHERE id = $1
`

func (q *Queries) GetFAQByID(ctx context.Context, id int64) (FaqItem, error) {
	row := q.db.QueryRow(ctx, getFAQByID, id)
	var i FaqItem
	err := row.Scan(
		&i.ID,
		&i.SortOrder,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKeyByKey = `-- name: GetIdempotencyKeyByKey :one
SELECT id, key, request_hash, response_body, created_at FROM idempotency_keys WHERE key = $1
`

func (q *Queries) GetIdempotencyKeyByKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyByKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentRedemptions = `-- name: GetRecentRedemptions :many
SELECT
    r.id,
    r.created_at,
    b.name AS batch_name,
    r.code_text AS code,
    r.user_id,
    r.result,
    r.message,
    r.webhook_status
FROM redemptions r
LEFT JOIN batches b ON b.id = r.batch_id
ORDER BY r.created_at DESC
LIMIT 8
`

type GetRecentRedemptionsRow struct {
	ID            int64            `json:"id"`
	CreatedAt     time.Time        `json:"created_at"`
	BatchName     *string          `json:"batch_name"`
	Code          string           `json:"code"`
	UserID        string           `json:"user_id"`
	Result        RedemptionResult `json:"result"`
	Message       string           `json:"message"`
	WebhookStatus WebhookStatus    `json:"webhook_status"`
}

func (q *Queries) GetRecentRedemptions(ctx context.Context) ([]GetRecentRedemptionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentRedemptionsRow
	for rows.Next() {
		var i GetRecentRedemptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.BatchName,
			&i.Code,
			&i.UserID,
			&i.Result,
			&i.Message,
			&i.WebhookStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedemptionByID = `-- name: GetRedemptionByID :one
SELECT id, code_id, batch_id, code_text, user_id, user_key, payload_snapshot, result, message, webhook_status, webhook_response, webhook_attempt, ip, idempotency_key, event_id, created_at FROM redemptions WHERE id = $1
`

func (q *Queries) GetRedemptionByID(ctx context.Context, id int64) (Redemption, error) {
	row := q.db.QueryRow(ctx, getRedemptionByID, id)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.BatchID,
		&i.CodeText,
		&i.UserID,
		&i.UserKey,
		&i.PayloadSnapshot,
		&i.Result,
		&i.Message,
		&i.WebhookStatus,
		&i.WebhookResponse,
		&i.WebhookAttempt,
		&i.Ip,
		&i.IdempotencyKey,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteLogo = `-- name: GetSiteLogo :one
SELECT
    logo_data,
    COALESCE(logo_content_type, '') AS logo_content_type,
    updated_at
FROM site_settings
WHERE singleton = true
  AND logo_data IS NOT NULL
`

type GetSiteLogoRow struct {
	LogoData        []byte    `json:"logo_data"`
	LogoContentType string    `json:"logo_content_type"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetSiteLogo(ctx context.Context) (GetSiteLogoRow, error) {
	row := q.db.QueryRow(ctx, getSiteLogo)
	var i GetSiteLogoRow
	err := row.Scan(&i.LogoData, &i.LogoContentType, &i.UpdatedAt)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT
    site_title,
    logo_content_type,
    updated_at
FROM site_settings
WHERE singleton = true
`

type GetSiteSettingsRow struct {
	SiteTitle       string    `json:"site_title"`
	LogoContentType *string   `json:"logo_content_type"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i GetSiteSettingsRow
	err := row.Scan(&i.SiteTitle, &i.LogoContentType, &i.UpdatedAt)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT
    (SELECT COUNT(*) FROM codes) AS codes_total,
    (SELECT COUNT(*) FROM codes WHERE use_count > 0) AS codes_used,
    (SELECT COUNT(*) FROM batches) AS batches,
    (SELECT COUNT(*) FROM redemptions WHERE result = 'success') AS redeem_total,
    (SELECT COUNT(*) FROM redemptions WHERE result = 'success' AND created_at >= DATE_TRUNC('day', NOW())) AS today,
    (SELECT COUNT(*) FROM redemptions WHERE webhook_status IN ('failed', 'dead_letter')) AS webhook_failed
`

type GetStatsRow struct {
	CodesTotal    int64 `json:"codes_total"`
	CodesUsed     int64 `json:"codes_used"`
	Batches       int64 `json:"batches"`
	RedeemTotal   int64 `json:"redeem_total"`
	Today         int64 `json:"today"`
	WebhookFailed int64 `json:"webhook_failed"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.CodesTotal,
		&i.CodesUsed,
		&i.Batches,
		&i.RedeemTotal,
		&i.Today,
		&i.WebhookFailed,
	)
	return i, err
}

const getUnusedCredential = `-- name: GetUnusedCredential :one
SELECT id, email, plan_type, expired, data, used, redemption_id, created_at, updated_at FROM credentials
WHERE used = false
  AND (expired IS NULL OR expired > NOW())
  AND ($1::text = '' OR plan_type = $1::text)
ORDER BY id ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetUnusedCredential(ctx context.Context, planType string) (Credential, error) {
	row := q.db.QueryRow(ctx, getUnusedCredential, planType)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PlanType,
		&i.Expired,
		&i.Data,
		&i.Used,
		&i.RedemptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAdminSessionVersion = `-- name: IncrementAdminSessionVersion :exec
UPDATE admins
SET session_version = session_version + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementAdminSessionVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementAdminSessionVersion, id)
	return err
}

const incrementCodeUseCount = `-- name: IncrementCodeUseCount :one
UPDATE codes
SET use_count = use_count + 1
WHERE id = $1
  AND status = 'unused'
  AND use_count < $2
RETURNING id, use_count
`

type IncrementCodeUseCountParams struct {
	ID       int64 `json:"id"`
	UseCount int32 `json:"use_count"`
}

type IncrementCodeUseCountRow struct {
	ID       int64 `json:"id"`
	UseCount int32 `json:"use_count"`
}

func (q *Queries) IncrementCodeUseCount(ctx context.Context, arg IncrementCodeUseCountParams) (IncrementCodeUseCountRow, error) {
	row := q.db.QueryRow(ctx, incrementCodeUseCount, arg.ID, arg.UseCount)
	var i IncrementCodeUseCountRow
	err := row.Scan(&i.ID, &i.UseCount)
	return i, err
}

const leaseWebhookOutboxEvent = `-- name: LeaseWebhookOutboxEvent :one
UPDATE webhook_outbox
SET
    status = 'pending',
    lease_token = $1,
    lease_expires_at = NOW() + INTERVAL '2 minutes',
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM webhook_outbox
    WHERE status IN ('pending', 'failed')
      AND scheduled_at <= NOW()
      AND (lease_expires_at IS NULL OR lease_expires_at <= NOW())
    ORDER BY scheduled_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, event_id, redemption_id, status, scheduled_at, lease_token, lease_expires_at, attempts, last_response, created_at, updated_at
`

func (q *Queries) LeaseWebhookOutboxEvent(ctx context.Context, leaseToken *string) (WebhookOutbox, error) {
	row := q.db.QueryRow(ctx, leaseWebhookOutboxEvent, leaseToken)
	var i WebhookOutbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.RedemptionID,
		&i.Status,
		&i.ScheduledAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.LastResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT
    b.id, b.name, b.description, b.payload_json, b.prefix, b.code_length, b.expires_at, b.max_uses_per_code, b.max_redeems_per_user, b.webhook_url, b.webhook_secret, b.status, b.created_at, b.updated_at, b.assign_credential, b.credential_plan_type,
    COUNT(c.id) AS code_count,
    COUNT(c.id) FILTER (WHERE c.use_count > 0) AS used_count
FROM batches b
LEFT JOIN codes c ON c.batch_id = b.id
GROUP BY b.id
ORDER BY b.created_at DESC
`

type ListBatchesRow struct {
	ID                 int64              `json:"id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	PayloadJson        json.RawMessage    `json:"payload_json"`
	Prefix             string             `json:"prefix"`
	CodeLength         int32              `json:"code_length"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	MaxUsesPerCode     int32              `json:"max_uses_per_code"`
	MaxRedeemsPerUser  int32              `json:"max_redeems_per_user"`
	WebhookUrl         string             `json:"webhook_url"`
	WebhookSecret      string             `json:"webhook_secret"`
	Status             BatchStatus        `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	AssignCredential   bool               `json:"assign_credential"`
	CredentialPlanType string             `json:"credential_plan_type"`
	CodeCount          int64              `json:"code_count"`
	UsedCount          int64              `json:"used_count"`
}

func (q *Queries) ListBatches(ctx context.Context) ([]ListBatchesRow, error) {
	rows, err := q.db.Query(ctx, listBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchesRow
	for rows.Next() {
		var i ListBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PayloadJson,
			&i.Prefix,
			&i.CodeLength,
			&i.ExpiresAt,
			&i.MaxUsesPerCode,
			&i.MaxRedeemsPerUser,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignCredential,
			&i.CredentialPlanType,
			&i.CodeCount,
			&i.UsedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodesByBatch = `-- name: ListCodesByBatch :many
SELECT c.id, c.batch_id, c.code, c.status, c.use_count, c.created_at,
    CASE
        WHEN c.status = 'disabled' THEN 'disabled'
        WHEN c.use_count >= b.max_uses_per_code THEN 'used'
        WHEN c.use_count > 0 THEN 'partused'
        ELSE 'active'
    END AS state
FROM codes c
JOIN batches b ON b.id = c.batch_id
WHERE c.batch_id = $1
ORDER BY c.id DESC
LIMIT $2 OFFSET $3
`

type ListCodesByBatchParams struct {
	BatchID int64 `json:"batch_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListCodesByBatchRow struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Code      string     `json:"code"`
	Status    CodeStatus `json:"status"`
	UseCount  int32      `json:"use_count"`
	CreatedAt time.Time  `json:"created_at"`
	State     string     `json:"state"`
}

func (q *Queries) ListCodesByBatch(ctx context.Context, arg ListCodesByBatchParams) ([]ListCodesByBatchRow, error) {
	rows, err := q.db.Query(ctx, listCodesByBatch, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodesByBatchRow
	for rows.Next() {
		var i ListCodesByBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Code,
			&i.Status,
			&i.UseCount,
			&i.CreatedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodesByBatchAndState = `-- name: ListCodesByBatchAndState :many
SELECT c.id, c.batch_id, c.code, c.status, c.use_count, c.created_at,
    CASE
        WHEN c.status = 'disabled' THEN 'disabled'
        WHEN c.use_count >= b.max_uses_per_code THEN 'used'
        WHEN c.use_count > 0 THEN 'partused'
        ELSE 'active'
    END AS state
FROM codes c
JOIN batches b ON b.id = c.batch_id
WHERE c.batch_id = $1
  AND (
      CASE
          WHEN c.status = 'disabled' THEN 'disabled'
          WHEN c.use_count >= b.max_uses_per_code THEN 'used'
          WHEN c.use_count > 0 THEN 'partused'
          ELSE 'active'
      END
  ) = $2::text
ORDER BY c.id DESC
LIMIT $4 OFFSET $3
`

type ListCodesByBatchAndStateParams struct {
	BatchID     int64  `json:"batch_id"`
	State       string `json:"state"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListCodesByBatchAndStateRow struct {
	ID        int64      `json:"id"`
	BatchID   int64      `json:"batch_id"`
	Code      string     `json:"code"`
	Status    CodeStatus `json:"status"`
	UseCount  int32      `json:"use_count"`
	CreatedAt time.Time  `json:"created_at"`
	State     string     `json:"state"`
}

func (q *Queries) ListCodesByBatchAndState(ctx context.Context, arg ListCodesByBatchAndStateParams) ([]ListCodesByBatchAndStateRow, error) {
	rows, err := q.db.Query(ctx, listCodesByBatchAndState,
		arg.BatchID,
		arg.State,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodesByBatchAndStateRow
	for rows.Next() {
		var i ListCodesByBatchAndStateRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Code,
			&i.Status,
			&i.UseCount,
			&i.CreatedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialPlans = `-- name: ListCredentialPlans :many
SELECT
    plan_type,
    COUNT(*) AS total,
    COUNT(*) FILTER (
        WHERE used = false AND (expired IS NULL OR expired > NOW())
    ) AS available,
    COUNT(*) FILTER (WHERE used = true) AS used,
    COUNT(*) FILTER (
        WHERE used = false AND expired IS NOT NULL AND expired <= NOW()
    ) AS expired
FROM credentials
GROUP BY plan_type
ORDER BY plan_type COLLATE "C"
`

type ListCredentialPlansRow struct {
	PlanType  string `json:"plan_type"`
	Total     int64  `json:"total"`
	Available int64  `json:"available"`
	Used      int64  `json:"used"`
	Expired   int64  `json:"expired"`
}

func (q *Queries) ListCredentialPlans(ctx context.Context) ([]ListCredentialPlansRow, error) {
	rows, err := q.db.Query(ctx, listCredentialPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialPlansRow
	for rows.Next() {
		var i ListCredentialPlansRow
		if err := rows.Scan(
			&i.PlanType,
			&i.Total,
			&i.Available,
			&i.Used,
			&i.Expired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, email, plan_type, expired, used, redemption_id, created_at, updated_at
FROM credentials
WHERE (
    $1::text = 'all'
    OR ($1::text = 'used' AND used = true)
    OR ($1::text = 'unused' AND used = false)
)
ORDER BY id DESC
LIMIT $3::integer OFFSET $2::integer
`

type ListCredentialsParams struct {
	StateFilter string `json:"state_filter"`
	PageOffset  int32  `json:"page_offset"`
	PageSize    int32  `json:"page_size"`
}

type ListCredentialsRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PlanType     string             `json:"plan_type"`
	Expired      pgtype.Timestamptz `json:"expired"`
	Used         bool               `json:"used"`
	RedemptionID *int64             `json:"redemption_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) ListCredentials(ctx context.Context, arg ListCredentialsParams) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials, arg.StateFilter, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsRow
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PlanType,
			&i.Expired,
			&i.Used,
			&i.RedemptionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFAQ = `-- name: ListFAQ :many
SELECT id, sort_order, title, content, created_at, updated_at FROM faq_items ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListFAQ(ctx context.Context) ([]FaqItem, error) {
	rows, err := q.db.Query(ctx, listFAQ)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaqItem
	for rows.Next() {
		var i FaqItem
		if err := rows.Scan(
			&i.ID,
			&i.SortOrder,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedemptions = `-- name: ListRedemptions :many
SELECT
    r.id,
    r.created_at,
    b.name AS batch_name,
    r.code_text AS code,
    r.user_id,
    r.result,
    r.message,
    r.webhook_status,
    r.webhook_response,
    host(r.ip) AS ip
FROM redemptions r
LEFT JOIN batches b ON b.id = r.batch_id
WHERE ($1::bigint = 0 OR r.batch_id = $1::bigint)
  AND ($2::text = '' OR r.result::text = $2::text)
  AND ($3::text = '' OR r.webhook_status::text = $3::text)
  AND ($4::text = '' OR r.user_key ILIKE '%' || $4::text || '%')
ORDER BY r.created_at DESC
LIMIT $6 OFFSET $5
`

type ListRedemptionsParams struct {
	BatchID       int64  `json:"batch_id"`
	ResultFilter  string `json:"result_filter"`
	WebhookFilter string `json:"webhook_filter"`
	UserFilter    string `json:"user_filter"`
	OffsetCount   int32  `json:"offset_count"`
	LimitCount    int32  `json:"limit_count"`
}

type ListRedemptionsRow struct {
	ID              int64            `json:"id"`
	CreatedAt       time.Time        `json:"created_at"`
	BatchName       *string          `json:"batch_name"`
	Code            string           `json:"code"`
	UserID          string           `json:"user_id"`
	Result          RedemptionResult `json:"result"`
	Message         string           `json:"message"`
	WebhookStatus   WebhookStatus    `json:"webhook_status"`
	WebhookResponse string           `json:"webhook_response"`
	Ip              string           `json:"ip"`
}

func (q *Queries) ListRedemptions(ctx context.Context, arg ListRedemptionsParams) ([]ListRedemptionsRow, error) {
	rows, err := q.db.Query(ctx, listRedemptions,
		arg.BatchID,
		arg.ResultFilter,
		arg.WebhookFilter,
		arg.UserFilter,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRedemptionsRow
	for rows.Next() {
		var i ListRedemptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.BatchName,
			&i.Code,
			&i.UserID,
			&i.Result,
			&i.Message,
			&i.WebhookStatus,
			&i.WebhookResponse,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdempotencyKeyByKey = `-- name: LockIdempotencyKeyByKey :one
SELECT id, key, request_hash, response_body, created_at FROM idempotency_keys WHERE key = $1 FOR UPDATE
`

func (q *Queries) LockIdempotencyKeyByKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKeyByKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const markCredentialUsed = `-- name: MarkCredentialUsed :one
UPDATE credentials
SET used = true, redemption_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, plan_type, expired, data, used, redemption_id, created_at, updated_at
`

type MarkCredentialUsedParams struct {
	ID           int64  `json:"id"`
	RedemptionID *int64 `json:"redemption_id"`
}

func (q *Queries) MarkCredentialUsed(ctx context.Context, arg MarkCredentialUsedParams) (Credential, error) {
	row := q.db.QueryRow(ctx, markCredentialUsed, arg.ID, arg.RedemptionID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PlanType,
		&i.Expired,
		&i.Data,
		&i.Used,
		&i.RedemptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const prepareRedemptionWebhookResend = `-- name: PrepareRedemptionWebhookResend :execrows
UPDATE redemptions
SET webhook_status = 'pending',
    webhook_response = '',
    event_id = $1
WHERE id = $2
  AND result = 'success'
  AND webhook_status IN ('success', 'failed', 'dead_letter')
`

type PrepareRedemptionWebhookResendParams struct {
	EventID *string `json:"event_id"`
	ID      int64   `json:"id"`
}

func (q *Queries) PrepareRedemptionWebhookResend(ctx context.Context, arg PrepareRedemptionWebhookResendParams) (int64, error) {
	result, err := q.db.Exec(ctx, prepareRedemptionWebhookResend, arg.EventID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderFAQ = `-- name: ReorderFAQ :exec
UPDATE faq_items
SET sort_order = s.ord
FROM unnest($1::bigint[]) WITH ORDINALITY AS s(id, ord)
WHERE faq_items.id = s.id
`

func (q *Queries) ReorderFAQ(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, reorderFAQ, dollar_1)
	return err
}

const setIdempotencyResponse = `-- name: SetIdempotencyResponse :exec
UPDATE idempotency_keys
SET response_body = $2
WHERE key = $1
`

type SetIdempotencyResponseParams struct {
	Key          string `json:"key"`
	ResponseBody []byte `json:"response_body"`
}

func (q *Queries) SetIdempotencyResponse(ctx context.Context, arg SetIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyResponse, arg.Key, arg.ResponseBody)
	return err
}

const toggleBatchStatus = `-- name: ToggleBatchStatus :one
UPDATE batches
SET status = CASE
    WHEN status = 'active' THEN 'disabled'::batch_status
    ELSE 'active'::batch_status
END
WHERE id = $1
RETURNING id, name, description, payload_json, prefix, code_length, expires_at, max_uses_per_code, max_redeems_per_user, webhook_url, webhook_secret, status, created_at, updated_at, assign_credential, credential_plan_type
`

func (q *Queries) ToggleBatchStatus(ctx context.Context, id int64) (Batch, error) {
	row := q.db.QueryRow(ctx, toggleBatchStatus, id)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PayloadJson,
		&i.Prefix,
		&i.CodeLength,
		&i.ExpiresAt,
		&i.MaxUsesPerCode,
		&i.MaxRedeemsPerUser,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignCredential,
		&i.CredentialPlanType,
	)
	return i, err
}

const toggleCodeStatus = `-- name: ToggleCodeStatus :one
UPDATE codes
SET status = CASE
    WHEN status = 'unused' THEN 'disabled'::code_status
    ELSE 'unused'::code_status
END
WHERE id = $1
RETURNING id, batch_id, code, status, use_count, created_at
`

func (q *Queries) ToggleCodeStatus(ctx context.Context, id int64) (Code, error) {
	row := q.db.QueryRow(ctx, toggleCodeStatus, id)
	var i Code
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Code,
		&i.Status,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const updateFAQ = `-- name: UpdateFAQ :one
UPDATE faq_items
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, sort_order, title, content, created_at, updated_at
`

type UpdateFAQParams struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) UpdateFAQ(ctx context.Context, arg UpdateFAQParams) (FaqItem, error) {
	row := q.db.QueryRow(ctx, updateFAQ, arg.ID, arg.Title, arg.Content)
	var i FaqItem
	err := row.Scan(
		&i.ID,
		&i.SortOrder,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRedemptionWebhookStatus = `-- name: UpdateRedemptionWebhookStatus :execrows
UPDATE redemptions
SET webhook_status = $1::webhook_status,
    webhook_response = $2,
    webhook_attempt = webhook_attempt + 1
WHERE id = $3
  AND event_id = $4
`

type UpdateRedemptionWebhookStatusParams struct {
	WebhookStatus   WebhookStatus `json:"webhook_status"`
	WebhookResponse string        `json:"webhook_response"`
	ID              int64         `json:"id"`
	EventID         *string       `json:"event_id"`
}

func (q *Queries) UpdateRedemptionWebhookStatus(ctx context.Context, arg UpdateRedemptionWebhookStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRedemptionWebhookStatus,
		arg.WebhookStatus,
		arg.WebhookResponse,
		arg.ID,
		arg.EventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSiteSettings = `-- name: UpdateSiteSettings :one
UPDATE site_settings
SET
    site_title = $1,
    logo_data = CASE
        WHEN $2::boolean
            THEN NULLIF($3::bytea, ''::bytea)
        ELSE logo_data
    END,
    logo_content_type = CASE
        WHEN $2::boolean
            THEN NULLIF($4::text, '')
        ELSE logo_content_type
    END
WHERE singleton = true
RETURNING
    site_title,
    logo_content_type,
    updated_at
`

type UpdateSiteSettingsParams struct {
	SiteTitle       string `json:"site_title"`
	UpdateLogo      bool   `json:"update_logo"`
	LogoData        []byte `json:"logo_data"`
	LogoContentType string `json:"logo_content_type"`
}

type UpdateSiteSettingsRow struct {
	SiteTitle       string    `json:"site_title"`
	LogoContentType *string   `json:"logo_content_type"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) (UpdateSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateSiteSettings,
		arg.SiteTitle,
		arg.UpdateLogo,
		arg.LogoData,
		arg.LogoContentType,
	)
	var i UpdateSiteSettingsRow
	err := row.Scan(&i.SiteTitle, &i.LogoContentType, &i.UpdatedAt)
	return i, err
}

const updateWebhookOutboxFailed = `-- name: UpdateWebhookOutboxFailed :execrows
UPDATE webhook_outbox
SET status = $1::webhook_status,
    last_response = $2,
    scheduled_at = $3,
    lease_token = NULL,
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE id = $4 AND lease_token = $5
`

type UpdateWebhookOutboxFailedParams struct {
	Status       WebhookStatus `json:"status"`
	LastResponse string        `json:"last_response"`
	ScheduledAt  time.Time     `json:"scheduled_at"`
	ID           int64         `json:"id"`
	LeaseToken   *string       `json:"lease_token"`
}

func (q *Queries) UpdateWebhookOutboxFailed(ctx context.Context, arg UpdateWebhookOutboxFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookOutboxFailed,
		arg.Status,
		arg.LastResponse,
		arg.ScheduledAt,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWebhookOutboxSuccess = `-- name: UpdateWebhookOutboxSuccess :execrows
UPDATE webhook_outbox
SET status = 'success',
    last_response = $1,
    lease_token = NULL,
    lease_expires_at = NULL,
    updated_at = NOW()
WHERE id = $2 AND lease_token = $3
`

type UpdateWebhookOutboxSuccessParams struct {
	LastResponse string  `json:"last_response"`
	ID           int64   `json:"id"`
	LeaseToken   *string `json:"lease_token"`
}

func (q *Queries) UpdateWebhookOutboxSuccess(ctx context.Context, arg UpdateWebhookOutboxSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookOutboxSuccess, arg.LastResponse, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserBatchUsage = `-- name: UpsertUserBatchUsage :one
INSERT INTO user_batch_usage (batch_id, user_key, used_count)
VALUES ($1, $2, 1)
ON CONFLICT (batch_id, user_key)
DO UPDATE SET used_count = user_batch_usage.used_count + 1
WHERE user_batch_usage.used_count < $3
RETURNING used_count
`

type UpsertUserBatchUsageParams struct {
	BatchID   int64  `json:"batch_id"`
	UserKey   string `json:"user_key"`
	UsedCount int32  `json:"used_count"`
}

func (q *Queries) UpsertUserBatchUsage(ctx context.Context, arg UpsertUserBatchUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertUserBatchUsage, arg.BatchID, arg.UserKey, arg.UsedCount)
	var used_count int32
	err := row.Scan(&used_count)
	return used_count, err
}
